### ISSUE TITLE
HMI file cannot be read by Nextion Editor

### ISSUE THREAD

**Issue by gerwin1967** [gijsje/ns-panel#1]
I would like to use a part of and learn on the way you set this up, however the nextion software states the following error:

"Wrong resource file or resource file has been damaged" 

can you upload a new one that functions.

**Comment by gijsje** [comment]
I downloaded the version on here and it loads just fine

**Comment by gerwin1967** [comment]
> 

Can you provide the info on the nextion editor software you use (version), as this might be the cause, I use V1.63.3

**Comment by gijsje** [comment]
Same here i uploaded my latest version

**Comment by gerwin1967** [comment]
Strange did not do any different and now it works .
